### ISSUE TITLE
 Internal compiler error: Segmentation fault

### ISSUE THREAD

**Issue by mertkiray** [chengzhag/Implicit3DUnderstanding#2]
Hello,

While building with `python project.py build`

I got the following error:

![image](https://user-images.githubusercontent.com/19538303/117564446-6462eb80-b0ac-11eb-9d2d-c19b8c6f6c8c.png)

`/usr/include/c++/10/chrono:473:154:   required from here
/usr/include/c++/10/chrono:428:27: internal compiler error: Segmentation fault
  428 |  _S_gcd(intmax_t __m, intmax_t __n) noexcept
      |                           ^~~~~~
`

My OS: Ubuntu 21.04
Shipped gcc version:10.3
Installed gcc version: 9.3.0
nvcc version: 11.2
Nvidia-smi: 
![image](https://user-images.githubusercontent.com/19538303/117564533-c7548280-b0ac-11eb-80e7-0a5404ad53cf.png)

Thanks for the help

**Comment by chengzhag** [comment]
Hi. 

It looks like that the problem happens when building the LDIF kernel provided by https://github.com/google/ldif. Thus we cannot provide a direct solution.
However, the LDIF kernel is not a must-have. You can still run our code following instructions in issue #1 without it.

**Comment by mertkiray** [comment]
One quick idea:
New RTX 30 series nvidia gpus require cuda toolkit >= 11.1 
But in the environment.yml this requirement is not met so the gpu cannot be utilized. 
Can we do a quick check?

**Comment by chengzhag** [comment]
The compiling of LDIF kernel might be using the nvcc installed on the system. But checking the cudatoolkit version of the conda environment might be a good starting point if any problem happens when running our code with RTX GPU. 

If the problem of compiling remains, you can always try the solution mentioned in issue #1. According to the observation of some other fellows, the CUDA kernel provides no improvement on RTX GPU thus might be not requisite.

**Comment by Fizmath** [comment]
You are using wrong Ubuntu with  **NVIDIA**  CUDA  .  Try on with   ``UBUNTU 20.04``.  </br>  **NVIDIA**  has tested  its latest GPU's  up to CUDA 11.3.0 with ``UBUNTU 20.04`` and ``UBUNTU 18.04``.
